import { Grid } from "@mui/material";
import Head from "next/head";
import Hero from "./../Components/Hero";
export default function Home() {
  return (
    <>
      <Head>
        <title>Charly Bozzola Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container justifyContent="center" padding={4}>
        <Grid
          container
          justifyContent="center"
          spacing={2}
          maxWidth="1204px"
          maxHeight="350px"
        >
          <Hero />
        </Grid>
      </Grid>
    </>
  );
}
