import { Grid } from "@mui/material";
import Head from "next/head";
import Hero from "./../Components/Hero";
import NavBar from "./../Components/Navbar";
export default function Home() {
  return (
    <>
      <Head>
        <title>Charly Bozzola Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        flexDirection="column"
        backgroundColor="#191919"
        height="100vh"
        alignItems="center"
      >
        <NavBar />
        <Hero />
      </Grid>
    </>
  );
}
